app/controllers/legacy_image_service_controller.rb, spec/controllers/legacy_image_service_controller_spec.rb
=> pass download=true querystring param along for legacy urls

app/controllers/iiif_controller.rb, spec/controllers/iiif_controller_spec.rb
per conversation with Stu and @azaroth42 , for better user experience
=> remove identifier from downloaded filename

app/controllers/media_controller.rb, spec/controllers/media_controller_spec.rb
=> media_controller: change 'view' to 'play' in login prompt text, update test

app/controllers/media_controller.rb, config/settings.yml, spec/cassettes/CORS_headers_for_Media_requests/_download/sets_the_Access-Control-Allow-Origin_header_correctly.yml, spec/cassettes/MediaController/_auth_check/sets_the_correct_CORS_headers.yml, spec/controllers/media_controller_spec.rb, spec/requests/media_headers_request_spec.rb
This is half of the work for sul-dlss/sul-embed#581. The other half is to update the Dash player to the latest version.
=> Set CORS headers for media.

spec/controllers/iiif_controller_spec.rb, spec/models/djatoka_metadata_spec.rb
I was working on these tests to be included with #73, but it was merged before I had a chance to finish them up.
=> Add a few tests now that we stub PURL XML a bit higher up the stack

app/controllers/media_controller.rb, spec/controllers/media_controller_spec.rb
_Note: this is currently deployed to the test/stage server_
=> Surface token via JSONP endpoint auth_check endpoint when successful.

config/initializers/is_it_working.rb
This is a continuation of PR #84, which was done in a rush due to production issues with load-balancer (which I sadly introduced with a previous modification to is_it_working, PR #70).
A failing "non-crucial" check not only returns 200 to the overall is_it_working status, but has an additional message that can be used to hopefully make it easier for PSMs to communicate with users/stakeholders.
This will allow the load balancer to check for status 200 while also allowing nagios to look for status 200 (for crucial alerts) and string matching on "FAIL" for non-crucial alerts.
This is analogous to the sul-embed PR: sul-dlss/sul-embed#652
Closes #83
=> is_it_working: refactor non_crucial url checks

Capfile, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/concerns/djatoka_adapter.rb, config/deploy.rb, config/initializers/squash.rb
Closes #79 
See sul-dlss/shared_configs#104 & sul-dlss/shared_configs#105 for honeybadger configs.
=> Replace Squash with Honeybadger for exception notification.

Gemfile, Gemfile.lock, config/initializers/okcomputer.rb, spec/features/status_spec.rb
=> add app monitoring with okcomputer at /status

Capfile, Gemfile, Gemfile.lock, config/deploy.rb
to get latest shared_config files with cap deploy.
woo hoo!  kudos to @jkeck
=> use capistrano-shared_configs 

README.md, config/deploy.rb, config/deploy/prod.rb
and shorten git url to the new shorter name for this github repo
=> cap deploy: add prod-c to prod boxes

.rubocop_todo.yml, app/controllers/iiif_controller.rb, config/initializers/mime_types.rb, config/routes.rb, spec/controllers/iiif_controller_spec.rb, spec/requests/iiif_spec.rb, spec/routing/iiif_routing_spec.rb
=> Assert IIIF level1 compliance

.rubocop_todo.yml, app/controllers/iiif_controller.rb, app/controllers/webauth_controller.rb, app/views/webauth/logout.html.erb, config/routes.rb, spec/controllers/iiif_controller_spec.rb, spec/controllers/webauth_controller_spec.rb, spec/routing/webauth_routing_spec.rb
Related to sul-dlss/puppet#2000
=> Advertise a iiif auth logout service; fixes #126

.rubocop_todo.yml, app/controllers/application_controller.rb, app/controllers/iiif_controller.rb, app/models/concerns/stacks_rights.rb, spec/controllers/iiif_controller_spec.rb, spec/models/stacks_rights_spec.rb, spec/requests/iiif_spec.rb
=> Advertise support for restricted locations; fixes #125

app/controllers/iiif_controller.rb, app/models/stacks_file.rb, app/models/stacks_image.rb, spec/models/stacks_image_spec.rb
=> Support the IIIF 2.1 max size parameter

app/models/ability.rb, config/settings/test.yml, spec/models/user_spec.rb
=> better authorization tests

app/controllers/application_controller.rb, app/controllers/iiif_controller.rb, app/controllers/iiif_token_controller.rb, app/models/user.rb, spec/controllers/iiif_controller_spec.rb, spec/controllers/iiif_token_controller_spec.rb
This needs manual testing, rspec tests, and thinking through whether it is a good idea at all.
=> Use the token service for location-based authentication

app/controllers/iiif_controller.rb, spec/controllers/iiif_controller_spec.rb
Closes https://github.com/sul-dlss/universalviewer/issues/32
Closes https://github.com/sul-dlss/universalviewer/issues/34
=> modify the login text and add failure for auth service

app/controllers/iiif_controller.rb, spec/controllers/iiif_controller_spec.rb
=> add required context

app/controllers/application_controller.rb, app/controllers/iiif_controller.rb, app/models/user.rb, spec/controllers/iiif_controller_spec.rb, spec/fixtures/rights_xml_fixtures.rb, spec/requests/iiif_auth_request_spec.rb, spec/requests/iiif_spec.rb
=> Add case for degraded logic for world no download and stanford only

.rubocop.yml, app/models/djatoka_image.rb, app/models/djatoka_path.rb, app/models/stacks_image.rb, app/services/djatoka_info_service.rb, app/services/info_service.rb, app/services/stacks_image_source_factory.rb, app/services/stacks_info_service_factory.rb, config/settings.yml, spec/services/djatoka_info_service_spec.rb
This add a configurable image source factory to extract Djatoka
=> Add Image source factory

app/models/ability.rb, app/models/concerns/stacks_rights.rb, spec/models/stacks_rights_spec.rb
=> Simplify ability

app/controllers/application_controller.rb, app/controllers/iiif_controller.rb, app/models/user.rb, spec/controllers/iiif_controller_spec.rb, spec/requests/iiif_spec.rb
removes generic_stanford_webauth_ability for degraded images
=> Replaces check for downloadable and accessible on degraded images

app/models/stacks_image.rb, app/services/djatoka_metadata_service.rb, app/services/iiif_metadata_service.rb, spec/models/stacks_image_spec.rb, spec/services/iiif_metadata_service_spec.rb
=> Force tiles to 256 on restricted images

app/services/iiif_metadata_service.rb, spec/services/iiif_metadata_service_spec.rb
=> Add a full size to the info response

app/controllers/iiif_controller.rb, app/models/stacks_identifier.rb, app/services/path_service.rb, spec/controllers/iiif_controller_spec.rb, spec/models/stacks_identifier_spec.rb
Fixes problems like this: https://app.honeybadger.io/projects/49299/faults/34727592#notice-summary
=> Validate the identifier before doing anything

app/models/projection.rb, spec/models/projection_spec.rb
This previously resulted in a Nil pointer error. This is slightly better: https://app.honeybadger.io/projects/49299/faults/34708899#notice-comments
=> Error on unexpected transformation

app/controllers/iiif_controller.rb, app/models/djatoka_image.rb, app/models/djatoka_path.rb, app/models/stacks_identifier.rb, app/services/remote_iiif_identifier.rb, spec/controllers/iiif_controller_spec.rb, spec/models/djatoka_image_spec.rb, spec/models/iiif_image_spec.rb, spec/models/stacks_identifier_spec.rb, spec/services/djatoka_metadata_service_spec.rb, spec/services/iiif_metadata_service_spec.rb
=> File name ext

app/models/stacks_identifier.rb, app/services/path_service.rb, app/services/remote_iiif_identifier.rb, spec/models/stacks_identifier_spec.rb
=> Treeified path

app/controllers/application_controller.rb
=> Refactor token_user callers to avoid blindly passing arguments to it

.rubocop.yml, app/controllers/iiif_controller.rb, app/models/iiif.rb, app/models/iiif/dimension.rb, app/models/iiif/region/absolute.rb, app/models/iiif/region/full.rb, app/models/iiif/region/percent.rb, app/models/iiif/region/square.rb, app/models/iiif/size/absolute.rb, app/models/iiif/size/best_fit.rb, app/models/iiif/size/full.rb, app/models/iiif/size/height.rb, app/models/iiif/size/max.rb, app/models/iiif/size/percent.rb, app/models/iiif/size/width.rb, app/models/projection.rb, app/models/restricted_image.rb, app/services/iiif/option_decoder.rb, spec/abilities/ability_spec.rb, spec/controllers/iiif_controller_spec.rb, spec/models/projection_spec.rb
=> Extract options parsing from Projection

config/environments/production.rb
=> Handle InvalidAttributeError as a bad request

app/models/source_image.rb, app/services/iiif_metadata_service.rb
=> Retry on network failure

config/environments/production.rb
=> Update the rescued error

app/services/iiif_metadata_service.rb, app/services/stacks/unexpected_metadata_response_error.rb, spec/services/iiif_metadata_service_spec.rb
This raises an error with the HTTP response is a 200 but the JSON received is invalid. 
Addressing issue #241
=> Raise an exception message with JSON is invalid.

app/models/stacks_file.rb, app/models/stacks_image.rb, spec/controllers/file_controller_spec.rb, spec/models/projection_spec.rb, spec/models/stacks_file_spec.rb, spec/requests/file_auth_request_spec.rb, spec/requests/iiif_auth_request_spec.rb, spec/requests/iiif_spec.rb
=> Switch exist? to readable? for StacksFiles

app/models/approved_location.rb, app/models/concerns/stacks_rights.rb, app/models/user.rb, app/services/media_authentication_json.rb, config/settings/test.yml, spec/models/approved_location_spec.rb, spec/models/user_spec.rb, spec/requests/iiif_auth_request_spec.rb, spec/services/media_authentication_json_spec.rb
=> Refactor users and rights to allow users that should have access to multiple location to access the location-restricted material

app/services/iiif_info_service.rb, config/settings.yml, spec/services/iiif_info_service_spec.rb
Fixes https://github.com/sul-dlss/sul-embed/issues/1097
I've  tested this locally by running stacks, purl, and mirador and can confirm the fix in Firefox and Safari.
=> Reduce tile size for exaggerated tilesizes

app/controllers/file_controller.rb, config/routes.rb, spec/requests/file_spec.rb
=> Permit Range header requests from CORS requests

.github/workflows/ruby.yml, Gemfile, Gemfile.lock, spec/controllers/cdl_controller_spec.rb
Pending zipline/zip_tricks compatibility
=> Test with Ruby 3

config/environments/production.rb
=> Re-enable X-Sendfile header

app/controllers/object_controller.rb, app/controllers/webauth_controller.rb, config/routes.rb, spec/controllers/object_controller_spec.rb
Fixes #949
Tested by Andrew on stage.
=> Force a login if any of the files in the zip are restricted

app/models/ability.rb, spec/abilities/ability_spec.rb
So we don't need to grant these permissions in the Ability class
=> StacksMediaStream is never authorized for read or download

app/controllers/iiif_token_controller.rb, spec/controllers/iiif_token_controller_spec.rb
Presently going to /image/iiif/token redirects to /image/iiif/token.js. This behavior is unnecessary
=> Remove unnecessary redirect

app/controllers/iiif/auth/v2/probe_service_controller.rb, spec/requests/iiif/auth/v2/probe_service_spec.rb
=> Guard against malformed URIs

app/controllers/iiif/auth/v2/probe_service_controller.rb, spec/requests/iiif/auth/v2/probe_service_spec.rb
=> Handle bad URIs gracefully

Gemfile.lock, app/models/storage_root.rb
=> Update to ocfl 0.9

spec/requests/iiif_spec.rb
=> Additional corrections of tested url

app/views/shared/_top_navbar.html.erb
Aligns with https://github.com/sul-dlss/component-library/pull/34
=> Reduce header vertical margin slightly

spec/rails_helper.rb
=> Use plural fixture path

app/controllers/iiif/auth/v2/probe_service_controller.rb, app/models/cocina.rb, config/settings.yml
part of https://github.com/sul-dlss/sul-embed/issues/2234
=> add wms location for geo login

app/controllers/iiif/auth/v2/probe_service_controller.rb, app/models/auth_probe_result2.rb, app/models/cocina.rb, app/models/cocina_ability.rb, app/models/stacks_file.rb, app/models/stacks_image.rb, app/models/stacks_media_stream.rb, app/models/stacks_rights.rb, config/locales/en.yml, spec/requests/iiif/auth/v2/probe_service_spec.rb
part of https://github.com/sul-dlss/sul-embed/issues/2783
=> return 403 for no download on pdf, 3d

app/controllers/iiif/auth/v2/probe_service_controller.rb, spec/requests/iiif/auth/v2/probe_service_spec.rb
part of https://github.com/sul-dlss/sul-embed/issues/2899
=> allow auth probe service to check old versions of files

app/controllers/iiif_controller.rb
=> add comment to make sure we don't remove legacy proxying

app/models/wowza_secure_token.rb
=> move timestamps to initializer
