sul-dlss/stacks

- .rubocop.yml
- app/controllers/application_controller.rb
- app/controllers/concerns/action_controller/http_authentication/bearer.rb
- app/controllers/iiif_controller.rb
- app/controllers/iiif_token_controller.rb
- app/models/user.rb
- config/routes.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/iiif_controller_spec.rb
- spec/controllers/iiif_token_controller_spec.rb
- spec/features/iiif_spec.rb
In f8125401e808b5d0090972692dae42af4424ce60, we added support for generating IIIF Authentication tokens, but were still relying on the login service to maintain a WebAuthed session. b2c8dbb finishes that work by supporting Bearer token authentication in addition to WebAuth + Basic Auth.
> Support IIIF Authentication for requesting resources

- app/models/stacks_file.rb
b/c it's too scary to mess with a method called "valid" in a model -- too much rails magic may be at work.  Probably the fix is to change it to file_exist?  but I am feeling wimpy.
> add FIXME comment to stacks_file model's valid method

- app/controllers/media_controller.rb
- app/models/stacks_media_token.rb
- config/routes.rb
- config/settings.yml
- spec/controllers/media_controller_spec.rb
- spec/models/stacks_media_token_spec.rb
- spec/routing/media_routing_spec.rb
PR #44 should probably be merged first, then this should get rebased on top of that.
* add a StacksMediaToken class for ephemeral authorization of access by a user to a StacksMediaStream.
* have MediaController#stream include an encrypted token string in its redirects.
* add MediaController#verify_token method (and route to it) to allow other services to verify tokens.
resolve #28
> Media stream token management

- app/controllers/media_controller.rb
- app/models/stacks_media_token.rb
- spec/controllers/media_controller_spec.rb
- spec/models/stacks_media_token_spec.rb
- spec/routing/media_routing_spec.rb
I think "token" is good enough as a param name, but if we *must* have something more than that, I think "stacks_token" is better than "token_string".
Also not sure of underscores vs camel case in HTTP GET params.  Which is another reason why shorter feels better to me.
I also did a separate commit shortening user_ip_addr  to user_ip
@jmartin-sul
> media token refactor:  token instead of token_string;  user_ip instead of user_ip_addr

- config/deploy.rb
- config/deploy/staging.rb
We need to be able to deploy to sul-stacks-test from a branch, and the debug logging was creating a lot of confusing noise in the deploy.
It looks like the old way to deploy a branch to "test" was to use an ENV variable - that isn't a pattern I've come across before ...
I am also keenly aware that our VM is called sul-stacks-test, but the cap deploy is "staging" -- shouldn't it be "test" or "stage" ?  Do we have standard practice here?  Is it not worth changing because the VM is "test" ?
> cap deploy prompts for branch and does info level logging

- .gitignore
- config/routes.rb
- spec/routing/file_routing_spec.rb
- spec/routing/iiif_routing_spec.rb
- spec/routing/media_routing_spec.rb
this builds on the work @ndushay started in 49-tests-for-special-chars-in-url. 
Note that it may not be perfectly what we want at this time, but it should be LESS BROKEN that our original filenames for media routes.
it:
* alters a couple file name parameter constraints to allow for special char handling in media streaming and download routes.
* adds a note about a limitation on usable file names for the download routes.
* does some rubocop mandated style cleanup on the tests naomi already added for special character handling in general across media, file, and iiif routing specs.
* refines some skip messages on some of the tests naomi added.
connects to #49
> handle special chars in download and stream URLs, add tests for special char handling in URLs in general

- app/controllers/application_controller.rb
- app/controllers/iiif_token_controller.rb
- app/models/user.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/iiif_token_controller_spec.rb
before the anonymous locatable user type was added, anonymous users weren't granted IIIF bearer tokens.  the addition of anonymous users introduced a regression:  previously, anonymous users would result in `nil` when `current_user` got called, but now `current_user` will never return nil, and so a caller would always get a token.
this PR fixes the regression by adding a flag indicating when a user is an anonymous locatable user, and checking that flag before the IIIF bearer token is issued.  it also adds a test for the new flag and fixes an old test so that it would've failed and caught the regression.
deployed to stacks-test.
paired w/ @jkeck
fixes sul-dlss/sul-embed#591
connect to sul-dlss/sul-embed#591
> don't grant IIIF bearer tokens to anonymous users

- config/settings.yml
set the default token expiry time to 45 seconds.
connects to sul-dlss/media#31
> default token expiry time of 45 seconds

- config/initializers/is_it_working.rb
per discussion in standup this morning, stacks isn't down if the image server is down -- only images in the stacks are down (not media, not files, ...)
> is_it_working: make djatoka_url a non_crucial check

- app/controllers/media_controller.rb
For Windows 10, Internet Explorer 11 and Edge seem to request the wrong content type when the jQuery Ajax request to the auth_check endpoint is issued (this happens when Sul-Embed tries to play a video or audio file). Since we actually only ever return JSON from auth_check, this PR simply hardcodes the response format without testing the actual format requested. This is an easy and seemingly foolproof way to please all browsers. This is the stacks-side of the fix for sul-dlss/media#122.
> Hardcode response format in auth_check, to please IE/Edge on Windows 10.

- config/initializers/okcomputer.rb
due to how OkComputer::CacheCheck expects the host name, we can't use it; always using GenericCacheCheck will ensure that the cache is working; we just won't get stats used in the result. No biggie.
connected to #96
> okcomputer: use GenericCacheCheck always as CacheCheck won't pass

- app/models/stacks_file.rb
I suspect this method was vestigial from some copy-paste that went bad, or something.
resolves #32
> stacks_file: remove valid? method as it made no sense

- app/controllers/application_controller.rb
- app/controllers/iiif_controller.rb
- app/controllers/iiif_token_controller.rb
- app/controllers/media_controller.rb
- app/views/iiif_token/create.html.erb
- config/settings.yml
- spec/controllers/iiif_controller_spec.rb
- spec/controllers/iiif_token_controller_spec.rb
> Implement IIIF Authentication 1.0 browse-based client application authentication

- app/controllers/iiif_controller.rb
- spec/controllers/iiif_controller_spec.rb
fix existing tests:  pull a more generally applicable `allow` out of the individual tile size test case and put it in a `before` in the `#metadata` section, so that all of those test cases are for downloadable images by default (previously didn't matter one way or the other for the extant profile test case, but matters now with this change).  add a test case that looks for `maxWidth` in `profile` when the image isn't downloadable.
closes #134
> IiifController#image_info: specify 'maxWidth' in 'profile' property when image is not downloadable

- app/controllers/iiif_controller.rb
- app/models/concerns/stacks_rights.rb
- app/models/purl.rb
- spec/fixtures/rights_xml_fixtures.rb
- spec/models/purl_spec.rb
- spec/requests/iiif_spec.rb
- spec/support/stub_rights_xml.rb
We should manually test this with sul-embed just to make sure it is ok with the redirects.
> Implement IIIF Auth 1.0 tiered access by redirecting to degraded info.json documents

- app/controllers/iiif_controller.rb
- spec/controllers/iiif_controller_spec.rb
UV currently does not have a fallback confirmLabel for its login dialog (see https://github.com/UniversalViewer/universalviewer/issues/484)
Without this, SUL resources in UV render "undefined" label:
> adds a confirmLabel to our IIIF auth responses

- app/controllers/iiif_controller.rb
- spec/controllers/iiif_controller_spec.rb
- spec/requests/iiif_spec.rb
When an image is not accessible, its height/width should be scaled
to a max dimension of 400px.
Closes https://github.com/sul-dlss/sul-embed/issues/803
Closes https://github.com/sul-dlss/sul-embed/issues/808
> Supports the use case where if an image is not accessible

- app/controllers/iiif_controller.rb
- spec/controllers/iiif_controller_spec.rb
- spec/requests/iiif_spec.rb
This reverts commit a858ca755be051d2894aa8c973c2f0006c85f22f.
This doesn't approach doesn't play nice with our ImageX viewer, resulting in the "wrong" tiles being loaded.
> Revert "Supports the use case where if an image is not accessible"

- app/models/djatoka_image.rb
- app/models/djatoka_metadata.rb
- app/services/stacks_image_source_factory.rb
- app/services/stacks_info_service_factory.rb
- config/initializers/okcomputer.rb
- config/settings.yml
- spec/models/djatoka_image_spec.rb
- spec/requests/iiif_auth_request_spec.rb
This moves driver specific settings into attribute values for the image and the info services. The image and info factories will now manage setting the attributes.
> Move djatoka_url in settings to driver.image.attributes.url

- app/models/iiif/image_request_uri.rb
Otherwise when the code is eager loaded (production mode) then it
resolves this as ::URI rather than Iiif::URI
> Give a fully qualified class name

- app/services/auth_service.rb
- spec/services/iiif_info_service_spec.rb
This PR addresses the empty dialogue issue reported in https://github.com/sul-dlss/sul-embed/issues/821
> adds auth service header and service

- app/controllers/iiif_controller.rb
- app/models/djatoka_image.rb
- app/models/iiif_image.rb
- app/models/projection.rb
- app/models/source_image.rb
- app/models/stacks_image.rb
- spec/controllers/iiif_controller_spec.rb
- spec/models/iiif_image_spec.rb
- spec/models/projection_spec.rb
- spec/models/stacks_image_spec.rb
- spec/requests/iiif_auth_request_spec.rb
- spec/requests/iiif_spec.rb
I think this was overlooked. The easiest way to do this is to just
acknowledge that `/stacks` is mounted.  This has the benefit of reducing
network calls.
Also move the `valid?` check to the Projection.
> Implement etag on images from iiif

- spec/controllers/media_controller_spec.rb
This regex was right most of the time, but not always.
> Fix a flappy spec

- app/models/projection.rb
- app/models/restricted_image.rb
- spec/models/projection_spec.rb
> Restrict the size of thumbnails and tiles when handling full/max requests

- app/services/iiif_metadata_service.rb
- lib/errors.rb
When the error is a 503, typically there is a load balancer problem
wheras when it's a 500 typically there is a malformed image that needs
to be corrected.  Splitting this into two different errors will help us
categorize these in Honeybadger.
> Differentiate 500 vs 503 responses from the image server

- config/environments/production.rb
This allows big files to be delivered by Apache rather than using a
Rails server process (which is more resource intensive)
Fixes #334
> Set the X-Sendfile header for mod_sendfile

- app/controllers/application_controller.rb
- app/controllers/webauth_controller.rb
- config/deploy/uat.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/webauth_controller_spec.rb
This allows shibboleth session information to be shared between the application servers.
> Store user information in the Rails session

- app/controllers/iiif_controller.rb
- spec/controllers/iiif_controller_spec.rb
Fixes https://github.com/sul-dlss/sul-embed/issues/1047. I believe this is valid syntax supported by most currenet browsers. There's significant disagreement about what legacy browsers do, but :shrug:
> Add quotes around the content disposition file name field

- app/models/restricted_image.rb
- app/services/iiif_info_service.rb
- config/settings.yml
- spec/models/restricted_image_spec.rb
- spec/requests/iiif_spec.rb
- spec/requests/remote_iiif_image_delivery_spec.rb
This is related to VUF-7343, but may require additional work in the mirador download plugin to resolve the reported issue.
Fixes https://github.com/sul-dlss/sul-embed/issues/1078.
> Include an aspect-ratio-respecting size for thumbnail images

- app/services/iiif_info_service.rb
- lib/tasks/test_images.rake
- spec/services/iiif_info_service_spec.rb
Part of https://github.com/sul-dlss/sul-embed/issues/739
Our image server isn't able to correctly process large images. These seem to approach 250,000,000 pixels.
This sets a maximum pixel allowance of 200,000,000 as a general threshold.
Some data about download requests here: https://docs.google.com/spreadsheets/d/1aKeievR9keJVS0TKGq70rPAY7I4CWKT7DpWZsYiLURI/edit#gid=0
> Filter the sizes that are returned from an info.json

- app/controllers/media_controller.rb
Part of the Rails 6 update enabled forgery protection by default (which is mostly for the good.. except also includes GET results for our JSON + XML APIs... )
> Also skip_forgery_protection on the media api

- app/controllers/media_controller.rb
It appears that (possibly due to default cipher changes in rails 6) that tokens now include characters that it didn't before (mainly "+" is what I'm seeing)
The tokens are currently not being encoded, which seems to have been fine, however with these "+" characters we're seeing that when being passed through a URL they're being decoded as a literal space instead of a +
This is causing the token to fail validation because " " != "+"
It seems like ensuring the token is encoded when being sent through the URL will ensure that the auto-decoded parameter we end up w/ in stacks is decoding the correct things.
This is currently deployed to stage (which is updated to Centos7) and uat.
> URL encode stacks auth tokens for media

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/cdl_controller.rb
- app/controllers/iiif_controller.rb
- app/controllers/iiif_token_controller.rb
- app/models/ability.rb
- app/models/concerns/stacks_rights.rb
- app/models/user.rb
- app/services/cdl_service.rb
- app/services/iiif_info_service.rb
- config/initializers/okcomputer.rb
- config/routes.rb
- config/settings.yml
- spec/abilities/ability_spec.rb
- spec/controllers/cdl_controller_spec.rb
- spec/controllers/file_controller_spec.rb
- spec/controllers/iiif_controller_spec.rb
- spec/models/user_spec.rb
- spec/routing/cdl_routing_spec.rb
- spec/services/iiif_info_service_spec.rb
- spec/services/media_authentication_json_spec.rb
This PR adds support for controlled digital lending  using the IIIF Auth  API. Items are "checked out" using the IIIF login auth pattern, forwards the user to sul-requests to perform the Symphony interactions, and returns to stacks with a JWT token that "authorizes" the viewer.
The basic version should work with any IIIF-capable viewer, but additional functionality will need to come from a custom viewer plugin.
> Support IIIF authentication  services for controlled digital lending

- app/models/source_image.rb
- app/services/iiif_metadata_service.rb
- spec/models/projection_spec.rb
- spec/requests/iiif_auth_request_spec.rb
- spec/services/iiif_metadata_service_spec.rb
We are removing the default HTTP gem URL normalization because there is
an upstream error which causes issues for `+` characters.
https://github.com/sporkmonger/addressable/issues/386
> Remove url normalization from our HTTP calls to the imageserver

- app/controllers/application_controller.rb
From https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html
> APIs may want to disable this behavior since they are typically designed to be state-less: that is, the request API client handles the session instead of Rails. One way to achieve this is to use the :null_session strategy instead, which allows unverified requests to be handled, but with an empty session.
> Configure protect_from_forgery to allow api requests

- app/controllers/file_controller.rb
- app/controllers/iiif_controller.rb
```
App 20356 output: /opt/app/stacks/stacks/shared/bundle/ruby/2.7.0/gems/actionpack-6.1.4.4/lib/action_controller/metal/conditional_get.rb:219: warning: The called method `stale?' is defined here
App 20376 output: /opt/app/stacks/stacks/releases/20220110172201/app/controllers/iiif_controller.rb:20: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
App 20376 output: /opt/app/stacks/stacks/shared/bundle/ruby/2.7.0/gems/actionpack-6.1.4.4/lib/action_controller/metal/conditional_get.rb:219: warning: The called method `stale?' is defined here
App 20314 output: /opt/app/stacks/stacks/releases/20220110172201/app/controllers/iiif_controller.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be …
```
> Send keyword parameters instead of a hash to fix some deprecation warnings

- app/models/restricted_image.rb
- app/models/stacks_image.rb
- spec/models/restricted_image_spec.rb
- spec/models/stacks_image_spec.rb
- spec/services/iiif_info_service_spec.rb
From https://iiif.io/api/image/2.1/compliance/#indicating-compliance
> Use the full URL for level 2 image API compliance

- app/controllers/file_controller.rb
This will allow stacks to embed this file as an object without having to retrieve it via `fetch` and processes it with PDF.js. We can just use the browsers built in PDF renderer.
> Remove X-Frame-Options from files#show

- app/models/stacks_media_stream.rb
- app/models/stacks_rights.rb
- app/services/media_authentication_json.rb
- spec/requests/media_auth_request_spec.rb
- spec/services/media_authentication_json_spec.rb
So that the media viewer can display an appropriate message to the user
> Support embargo response from the media auth service

- app/controllers/file_controller.rb
- app/models/ability.rb
- spec/abilities/ability_spec.rb
Then we can completely remove :read access for StacksFiles.  This removes a bunch of redundant actions from the Ability class.
> File controller should check for download access

- app/controllers/concerns/current_user_concern.rb
- app/controllers/iiif_token_controller.rb
- app/models/user.rb
- config/settings/test.yml
- spec/abilities/ability_spec.rb
- spec/controllers/application_controller_spec.rb
- spec/controllers/iiif_controller_spec.rb
This was used many years ago, but it's no longer useful as SDR has no agent-level access
> Remove unused basic auth path

- app/models/projection.rb
- spec/models/projection_spec.rb
Closes https://github.com/sul-dlss/sul-embed/issues/1604 
What this pull request does:
- For requests that ask for an explicit width and height combination that is larger than the original image size, this code uses the original image size in the IIIF image request instead.  
- Code already existed to handle restricted images (which relate to user permissions).  That code has been updated and repurposed to check for this situation and use the original image size. 
- The type of image class seems to be different between the restricted image use case and these full size image requests.  The former has a different method for calculating image size, so the code checks which method is available and uses the appropriate one.
> handling dimensions that are too large

- Dockerfile
We do this so Stacks can serve files (caption files, media files, etc.) directly without needing e.g. Wowza or passenger
> Run container in development env

- app/controllers/legacy_image_service_controller.rb
- config/environments/test.rb
- spec/controllers/legacy_image_service_controller_spec.rb
- spec/requests/legacy_image_service_spec.rb
Don't cast user input to float or integer without sanitizing
Fixes #1056
> Sanitize inputs

- spec/requests/iiif/auth/v2/probe_service_spec.rb
Follow on from #1067 to verify location label lookup works with `m&m` location.
Note that it requires this location string to be properly escaped in the rights XML, and I verified our PublishService does correctly generate the escaped location.
> verify location rights work with properly escaped m&m location

- app/controllers/iiif/auth/v2/probe_service_controller.rb
- spec/requests/iiif/auth/v2/probe_service_spec.rb
1. When a filename in the URI has spaces in it, they need to be decoded properly (from the encoded filename) before constructing the StacksFile object so that the file can be found on disk.
2. If the file is not readable on stacks, return a 404 in the status of the response body.
> deal with encoded spaces in filenames

- app/models/projection.rb
- spec/models/projection_spec.rb
Closes #1082 and https://github.com/sul-dlss/sul-embed/issues/1949. 
Context:
We had to revert an earlier commit for asking the IIIF server for the original size of an image when the requested dimensions were larger than the original image size: https://github.com/sul-dlss/stacks/pull/1070 .  With this original change, requests for percentage regions were resulting in an error documented here: https://github.com/sul-dlss/stacks/issues/1069 .  e.g. when the request looks like https://stacks.stanford.edu/image/iiif/cp798vs8827/6855100/pct:3,3,77,77/full/0/default.jpg .
Explanation of error:
As part of the original changes, we added a check for "use_original_size?" in the real_transformation method.  This check executed "max_tile_dimensions" on the image object which in turn executes …
> Checking for requested image dimensions while preventing percentage errors

- app/controllers/iiif/auth/v2/probe_service_controller.rb
- app/models/stacks_file.rb
- spec/requests/iiif/auth/v2/probe_service_spec.rb
This will give us a better message if the druid: prefix should sneak in
> Add a validator on stacks files

- config/application.rb
- config/environments/production.rb
This allows sul-embed to open an iframe to stacks and it will have the stacks session cookie passed with the request.
We have to do this because Chrome and safari now default to Lax, which doesn't allow us to do the behavior we want.  In order to use SameSite=None, you also must mark the cookie Secure.
> Set cookies SameSite=None

- app/controllers/media_controller.rb
In doing some work in https://github.com/sul-dlss/stacks/pull/1068 and https://github.com/sul-dlss/sul-embed/pull/2032, I discovered that setting the CORs header in the media controller may be duplicative and not necessary.  This just adds a comment for potential future removal if/when media authorization flow is refactored to make use of the new IIIF auth methods in stacks.
> add code comment about possible duplication of CORs header code

- app/models/stacks_rights.rb
- spec/requests/iiif_spec.rb
> Return 404 when the iiif endpoint is called for a file on a collection

- app/models/stacks_media_token.rb
- app/models/user.rb
Rails.application.secrets is deprecated and issues a bunch of warnings.
> Avoid accessing secret__key_base via secrets

- spec/requests/iiif_spec.rb
The url under test is not valid and only works because of excessive stubbing in this test. Compare:
* https://stacks.stanford.edu/image/iiif/nr349ct7889/nr349ct7889_00_0001/info.json
* https://stacks.stanford.edu/image/iiif/nr349ct7889/nr349ct7889_00_0001.jp2/info.json
> Fix tested url

- config/application.rb
- config/initializers/new_framework_defaults_7_1.rb
This prevents a deprecation warning about the cache format we are using
> Switch to using rails 7.0 defaults

- config/environments/test.rb
This avoids running background jobs inline, which cause a bunch of WebMock errors to be logged
> Set the active_job test adapter

- app/models/cocina.rb
This reverts part of d693909c09f2cd2f1c5f72d81d31d53f90ebf4db so that we aren't invalidating the entire cache
> Cache data rather than ruby object

- app/models/cocina.rb
- config/routes.rb
- spec/models/cocina_spec.rb
- spec/requests/versioned_file_spec.rb
> Update paths for versionable routes

- config/routes.rb
- spec/routing/file_routing_spec.rb
It seems these might have been from Agent auth restrictions, which were removed when the repository was converted to Cocina.
> Remove unused routes

- .rubocop.yml
- app/models/cocina.rb
- app/models/iiif_image.rb
- app/services/iiif_metadata_service.rb
- app/services/metrics_service.rb
- config/initializers/okcomputer.rb
- config/settings.yml
- spec/controllers/object_controller_spec.rb
- spec/models/projection_spec.rb
- spec/requests/iiif_auth_request_spec.rb
- spec/services/iiif_metadata_service_spec.rb
> Add timeouts to try to stop things from jamming up if image server or /stacks aren't available

- Gemfile
- Gemfile.lock
- app/controllers/object_controller.rb
- app/models/cocina.rb
Because zipline is not yet compatable with the latest version of Rails.  It also has many features that we don't use. Fixes #1311
> Remove dependency on zipline

- .github/workflows/ruby.yml
> Use builtin bundler caching for the build.

- app/controllers/application_controller.rb
We have a lot of requests from stealth-bots that are overloading the imageserver and causing honeybadger alerts.  These bots often pretend to be a random version of Chrome.  By only allowing the modern versions of browsers, we remove a bunch of requests we don't care about. https://github.com/rails/rails/blob/e3cf59212be585df91e1f1ccc7b76d08fb28402b/actionpack/lib/action_controller/metal/allow_browser.rb\#L75
> Restrict to modern browsers

- app/controllers/iiif/auth/v2/probe_service_controller.rb
- app/controllers/media_controller.rb
- app/models/stacks_file.rb
- app/models/stacks_media_stream.rb
- spec/controllers/media_controller_spec.rb
- spec/requests/media_headers_request_spec.rb
We were previously returning the wrong token in IIIF v2 auth
> Return the token for the resource not for the user

- app/controllers/iiif/auth/v2/probe_service_controller.rb
- app/models/auth_probe_result2.rb
- spec/requests/iiif/auth/v2/probe_service_spec.rb
This fixes the rubocop errors and separates the formatting of the response out of the controller. 
This also removes `auth_url`, which is not a valid property of the probe service response (https://iiif.io/api/auth/2.0/#probe-service-response) and was not used.
> [refactor] Extract AuthProbeResult2 class

- app/controllers/iiif/auth/v2/probe_service_controller.rb
- app/models/stacks_file.rb
- app/models/stacks_media_stream.rb
This token is only used for media streams, so it oughtn't be in StacksFile
> Move token generation into StacksMediaStream

- app/services/iiif_metadata_service.rb
TimeoutError does not extend from ConnectionError, so we need to add it too. See https://github.com/httprb/http/blob/1af3c8e2dfb84d73e7febaaffce7bd7f4829cced/lib/http/errors.rb\#L39C31-L39C43
> Retry on timeout errors

- app/controllers/iiif_controller.rb
- app/services/iiif_info_service.rb
- spec/requests/iiif_spec.rb
- spec/services/iiif_info_service_spec.rb
part of #1422 
Before degraded info.json
After
> fix degraded info.json to display correct dimensions, sizes

- app/controllers/iiif_controller.rb
- app/services/iiif_info_service.rb
- spec/requests/iiif_spec.rb
- spec/services/iiif_info_service_spec.rb
This reverts commit 7b41052c11dbc86d7db02012e2f55a49acd3e461.
For some reason it is only showing portions of the image
> Revert "fix degraded info.json to display correct dimensions, sizes"

- app/services/iiif_metadata_service.rb
- lib/stacks.rb
Otherwise these are coded as RetrieveMetadataError, which doesn't make it clear that this is an error coming from the load balancer
> Add a special error when we have 502
